#!/bin/bash

if [ $# -ne 1 ];then
    printf "\n$0 <nmap output ports>\n\n";exit 1; fi

clear
printf "ICAgICAgICAgICAgICAgICAgICAgICAgLjggCiAgICAgICAgICAgICAgICAgICAgICAuODg4CiAgICAgICAgICAgICAgICAgICAgLjg4ODgnCiAgICAgICAgICAgICAgICAgICAuODg4OCcKICAgICAgICAgICAgICAgICAgIDg4OCcKICAgICAgICAgICAgICAgICAgIDgnCiAgICAgIC44ODg4ODg4ODg4OC4gLjg4ODg4ODg4ODg4LgogICAuODg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4OC4KIC44ODg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4LgouJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJwomJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJicKJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJicKQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAOgpAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEA6ICAgICAgICAgIDxncG9ydHMuc2ggdjEuMD4KQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAOgolJSUlJSUlJSUlJSUlJSUlJSUlJSUlJSUlJSUlJSUlLgolJSUlJSUlJSUlJSUlJSUlJSUlJSUlJSUlJSUlJSUlJS4KYCUlJSUlJSUlJSUlJSUlJSUlJSUlJSUlJSUlJSUlJSUlJS4KIGAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMCcKICBgMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwJwogICBgMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMCcKICAgICBgIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjJwogICAgICAgYCMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjJwogICAgICAgICBgIyMjIyMjIyMjJycjIyMjIyMjIycKICAgICAgICAgICBgIiIiIiIiJyAgYCIiIiIiJwo=" | base64 -d 
ports=$(echo "$1" | grep open | awk '{print $1}' | cut -d'/' -f1 | tr '\n' ',' | sed s/.$//g)
printf "\nsudo nmap -sSV -Pn -T4 -vvv -p$ports <host>"
printf "\nsudo nmap -sSVC -Pn -T4 -vvv -p$ports <host>"
